name: funmi Git action
run-name: funmi Git Action
on: [push]
jobs: 
  simple_test_for_now:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code from repo
    - uses: actions/checkout@v4

    - name: Set up mterraform to implement cloud infra"
      uses: hashicorp/setup-terraform@v2
      with: 
        terraform_version: 1.3.0

    - name: Terraform init
      run: terraform init
      
