name: funmi Git action
run-name: funmi Git Action
on: [push]
jobs: 
  simple_test_for_now:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_code_from_repo
       uses: actions/checkout@v4
    - run: echo "hello everyone"
    